export {default as App} from './App.js'
export {default as AllCampus} from './AllCampus'
export {default as AllStudents} from './AllStudent'
export {default as Home} from './Home'
export {default as ACampus} from './ACampus'